// Copyright ZeroLight ltd. All Rights Reserved.
#pragma once

#include "Runtime/Launch/Resources/Version.h"

#define UNREAL_5_5_OR_NEWER (ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 5)
#define UNREAL_5_4_OR_NEWER (ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 4)
#define UNREAL_5_3_OR_NEWER (ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 3)
#define UNREAL_5_2_OR_NEWER (ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 2)
#define UNREAL_5_1_OR_NEWER (ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 1)
#define UNREAL_5_0_OR_NEWER (ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 0)


